# Generated by Django 5.2 on 2025-04-15 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="catalog",
            old_name="name",
            new_name="name_en",
        ),
        migrations.AddField(
            model_name="catalog",
            name="name_ru",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="catalog",
            name="name_uz",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
