# Generated by Django 5.2 on 2025-04-16 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_rename_name_catalog_name_en_catalog_name_ru_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="document",
            old_name="file_name",
            new_name="file_name_en",
        ),
        migrations.AddField(
            model_name="document",
            name="file_name_ru",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="file_name_uz",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
