# Generated by Django 4.2.11 on 2025-04-16 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_rename_file_name_document_file_name_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="catalog",
            name="odoo_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="discount",
            name="odoo_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="option",
            name="odoo_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="odoo_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="productoption",
            name="odoo_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="productrating",
            name="odoo_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="producttemplate",
            name="odoo_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="variant",
            name="odoo_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
