# Generated by Django 4.2.11 on 2025-04-17 12:49

import app.models.product
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_basket_odoo_id_basketitem_odoo_id_booking_odoo_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="producttemplate",
            name="image",
            field=models.ImageField(
                default="default_image.jpg",
                upload_to=app.models.product.product_template_upload_to,
            ),
        ),
        migrations.AddField(
            model_name="producttemplate",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=16),
        ),
    ]
