# Generated by Django 5.2 on 2025-04-18 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_producttemplate_image_producttemplate_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="latitude",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="longitude",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("PENDING", "Pending"),
                    ("COMPLETED", "Completed"),
                    ("REFAUND", "Refaund"),
                    ("FAILED", "Failed"),
                ],
                max_length=20,
            ),
        ),
    ]
