# Generated by Django 5.2 on 2025-04-18 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_region_district"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="order",
            name="location",
        ),
        migrations.RemoveField(
            model_name="order",
            name="longitude",
        ),
        migrations.RemoveField(
            model_name="order",
            name="map_link",
        ),
        migrations.RemoveField(
            model_name="producttemplate",
            name="type",
        ),
        migrations.AddField(
            model_name="order",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="district",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="app.district",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="app.region",
            ),
        ),
    ]
