# Generated by Django 5.2 on 2025-04-19 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_remove_order_latitude_remove_order_location_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="option",
            name="additional_price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=16),
        ),
        migrations.AddField(
            model_name="producttemplate",
            name="on_hand",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="product",
            name="amount",
            field=models.FloatField(default=0.0),
        ),
    ]
