# Generated by Django 5.2 on 2025-04-19 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_option_additional_price_producttemplate_on_hand_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productoption",
            name="odoo_id",
        ),
    ]
