# Generated by Django 4.2.11 on 2025-04-22 06:22

import app.models.notification
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_remove_productoption_odoo_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="image",
            field=models.ImageField(
                blank=True, upload_to=app.models.notification.notification_upload_to
            ),
        ),
    ]
