# Generated by Django 4.2.11 on 2025-04-22 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0013_brand_remove_producttemplate_catalog_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="message",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="title",
        ),
        migrations.AddField(
            model_name="notification",
            name="message_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="message_ru",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="message_uz",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="title_en",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="title_ru",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="title_uz",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
