# Generated by Django 5.2 on 2025-04-24 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0014_remove_notification_message_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CASH", "Cash"),
                    ("INSTALLMENT", "Installment"),
                    ("MULTICARD", "Multicard"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
