# Generated by Django 4.2.11 on 2025-04-24 10:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0016_alter_discount_product_alter_discount_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="send_users",
            field=models.ManyToManyField(
                blank=True,
                related_name="notifications_sent",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
