# Generated by Django 4.2.11 on 2025-04-26 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0018_order_uuid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="basket",
            name="price",
        ),
        migrations.RemoveField(
            model_name="basketitem",
            name="price",
        ),
        migrations.RemoveField(
            model_name="basketitem",
            name="total_price",
        ),
    ]
