# Generated by Django 4.2.11 on 2025-04-26 12:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0019_remove_basket_price_remove_basketitem_price_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="promocode",
            name="user",
        ),
        migrations.AddField(
            model_name="promocode",
            name="users",
            field=models.ManyToManyField(
                related_name="promocodes", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="promocode",
            name="code",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
