# Generated by Django 4.2.11 on 2025-04-26 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0020_remove_promocode_user_promocode_users_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="promocode",
            name="max_usage_per_user",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="promocode",
            name="users",
            field=models.ManyToManyField(
                blank=True, related_name="promocodes", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.CreateModel(
            name="PromoCodeUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("used_at", models.DateTimeField(auto_now_add=True)),
                (
                    "promocode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.promocode"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="promocode",
            name="user_by_users",
            field=models.ManyToManyField(
                related_name="used_promocodes",
                through="app.PromoCodeUsage",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
