# Generated by Django 4.2.11 on 2025-04-28 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0021_promocode_max_usage_per_user_alter_promocode_users_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="basket",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="basketitem",
            name="price",
            field=models.DecimalField(decimal_places=2, default=20000.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="basketitem",
            name="total_price",
            field=models.DecimalField(decimal_places=2, default=40000.0, max_digits=12),
            preserve_default=False,
        ),
    ]
