# Generated by Django 4.2.11 on 2025-04-29 10:52

import app.models.product
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0022_basket_price_basketitem_price_basketitem_total_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("odoo_id", models.CharField(blank=True, max_length=255, null=True)),
                ("title", models.CharField(max_length=255)),
                (
                    "image",
                    models.ImageField(upload_to=app.models.product.offer_upload_to),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "products",
                    models.ManyToManyField(related_name="offers", to="app.product"),
                ),
            ],
        ),
    ]
