# Generated by Django 4.2.11 on 2025-04-29 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0023_offer"),
    ]

    operations = [
        migrations.AddField(
            model_name="branch",
            name="name",
            field=models.CharField(
                default="This is default, Change meee", max_length=400, unique=True
            ),
            preserve_default=False,
        ),
    ]
