# Generated by Django 4.2.11 on 2025-04-29 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0024_branch_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="offer",
            name="title",
        ),
        migrations.AddField(
            model_name="offer",
            name="title_en",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="offer",
            name="title_ru",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="offer",
            name="title_uz",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
