# Generated by Django 4.2.11 on 2025-04-30 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0025_remove_offer_title_offer_title_en_offer_title_ru_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="card",
            old_name="cardId",
            new_name="card_token",
        ),
        migrations.RemoveField(
            model_name="card",
            name="balance",
        ),
        migrations.RemoveField(
            model_name="card",
            name="expiration_date",
        ),
        migrations.RemoveField(
            model_name="card",
            name="userId",
        ),
    ]
