# Generated by Django 4.2.11 on 2025-04-30 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0026_rename_cardid_card_card_token_remove_card_balance_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="check",
            name="card_number",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
