# Generated by Django 5.2 on 2025-05-02 09:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0027_alter_check_card_number"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BranchWorkingDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("odoo_id", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "day",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ]
                    ),
                ),
                ("is_open", models.BooleanField(default=True)),
                ("opening_time", models.TimeField(default="09:00")),
                ("closing_time", models.TimeField(default="17:00")),
                ("lunch_start", models.TimeField(blank=True, null=True)),
                ("lunch_end", models.TimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ("day",),
            },
        ),
        migrations.AlterModelOptions(
            name="booking",
            options={"ordering": ["start_time"]},
        ),
        migrations.RemoveField(
            model_name="branch",
            name="day_from",
        ),
        migrations.RemoveField(
            model_name="branch",
            name="day_to",
        ),
        migrations.RemoveField(
            model_name="branch",
            name="time_from",
        ),
        migrations.RemoveField(
            model_name="branch",
            name="time_to",
        ),
        migrations.AddField(
            model_name="booking",
            name="cancellation_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="branch",
            name="daily_capacity",
            field=models.PositiveIntegerField(
                default=10, help_text="Maximum oil changes per day"
            ),
        ),
        migrations.AddField(
            model_name="branch",
            name="oil_change_duration",
            field=models.PositiveIntegerField(
                default=30,
                help_text="Duration in minutes for oil change appointments",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to="app.branch",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="car",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to="app.car",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("CONFIRMED", "Confirmed"),
                    ("CANCELLED", "Cancelled"),
                    ("COMPLETED", "Completed"),
                    ("NO_SHOW", "No Show"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["start_time"], name="app_booking_start_t_b103cc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(fields=["status"], name="app_booking_status_e0fa34_idx"),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["branch", "start_time"], name="app_booking_branch__802d4a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["user", "start_time"], name="app_booking_user_id_463a5a_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.UniqueConstraint(
                fields=("branch", "start_time", "car"),
                name="unique_booking_slot_per_car",
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.UniqueConstraint(
                fields=("branch", "start_time", "user"),
                name="unique_booking_slot_per_user",
            ),
        ),
        migrations.AddField(
            model_name="branchworkingday",
            name="branch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="working_days",
                to="app.branch",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="branchworkingday",
            unique_together={("branch", "day")},
        ),
    ]
