# Generated by Django 5.2 on 2025-05-02 10:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0028_branchworkingday_alter_booking_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="booking",
            name="unique_booking_slot_per_car",
        ),
        migrations.RemoveConstraint(
            model_name="booking",
            name="unique_booking_slot_per_user",
        ),
        migrations.RemoveField(
            model_name="branch",
            name="daily_capacity",
        ),
        migrations.AddField(
            model_name="branch",
            name="slot_capacity",
            field=models.PositiveIntegerField(
                default=3, help_text="Maximum simultaneous bookings per time slot"
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["CONFIRMED", "PENDING"])),
                fields=("branch", "start_time", "user"),
                name="unique_user_booking_per_slot",
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["CONFIRMED", "PENDING"])),
                fields=("branch", "start_time", "car"),
                name="unique_car_booking_per_slot",
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "PENDING")),
                fields=("branch", "start_time", "user", "car"),
                name="unique_booking_combo",
            ),
        ),
    ]
