# Generated by Django 5.2 on 2025-05-03 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0029_remove_booking_unique_booking_slot_per_car_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("odoo_id", models.CharField(blank=True, max_length=255, null=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "duration",
                    models.PositiveIntegerField(
                        default=30, help_text="Duration in minutes"
                    ),
                ),
                (
                    "slot_capacity",
                    models.PositiveIntegerField(
                        default=1, help_text="Max simultaneous bookings per slot"
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AppointmentWorkingDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("odoo_id", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "day",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ]
                    ),
                ),
                ("is_open", models.BooleanField(default=True)),
                ("opening_time", models.TimeField(default="09:00")),
                ("closing_time", models.TimeField(default="17:00")),
                ("lunch_start", models.TimeField(blank=True, null=True)),
                ("lunch_end", models.TimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ("day",),
            },
        ),
        migrations.AlterUniqueTogether(
            name="branchworkingday",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="branchworkingday",
            name="branch",
        ),
        migrations.RemoveConstraint(
            model_name="booking",
            name="unique_user_booking_per_slot",
        ),
        migrations.RemoveConstraint(
            model_name="booking",
            name="unique_car_booking_per_slot",
        ),
        migrations.RemoveConstraint(
            model_name="booking",
            name="unique_booking_combo",
        ),
        migrations.RemoveField(
            model_name="branch",
            name="oil_change_duration",
        ),
        migrations.RemoveField(
            model_name="branch",
            name="slot_capacity",
        ),
        migrations.AddField(
            model_name="appointment",
            name="branch",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointment",
                to="app.branch",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="appointment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to="app.appointment",
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["appointment", "start_time"],
                name="app_booking_appoint_df3e88_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["CONFIRMED", "PENDING"])),
                fields=("appointment", "start_time", "user"),
                name="unique_user_booking_per_appointment_slot",
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("status__in", ["CONFIRMED", "PENDING"]), ("car__isnull", False)
                ),
                fields=("appointment", "start_time", "car"),
                name="unique_car_booking_per_appointment_slot",
            ),
        ),
        migrations.AddField(
            model_name="appointmentworkingday",
            name="appointment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="working_days",
                to="app.appointment",
            ),
        ),
        migrations.DeleteModel(
            name="BranchWorkingDay",
        ),
        migrations.AlterUniqueTogether(
            name="appointmentworkingday",
            unique_together={("appointment", "day")},
        ),
    ]
