# Generated by Django 5.2 on 2025-05-03 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0030_appointment_appointmentworkingday_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CASH", "Cash"),
                    ("INSTALLMENT", "Installment"),
                    ("MULTICARD", "Multicard"),
                    ("CARD", "Card"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
