# Generated by Django 4.2.11 on 2025-05-04 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0031_alter_order_payment_method"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("odoo_id", models.IntegerField(blank=True, null=True, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("complete_name", models.CharField(max_length=255)),
                (
                    "location_type",
                    models.CharField(
                        choices=[
                            ("view", "View"),
                            ("internal", "Internal"),
                            ("customer", "Customer"),
                            ("inventory", "Inventory"),
                            ("production", "Production"),
                            ("supplier", "Supplier"),
                        ],
                        max_length=20,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("last_sync", models.DateTimeField(blank=True, null=True)),
                (
                    "parent_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="child_locations",
                        to="app.location",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WareHouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("odoo_id", models.IntegerField(blank=True, null=True, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=10)),
                ("active", models.BooleanField(default=True)),
                ("last_sync", models.DateTimeField(blank=True, null=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="warehouses",
                        to="app.branch",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StockQuant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("odoo_id", models.IntegerField(blank=True, null=True, unique=True)),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "reserved_quantity",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("last_sync", models.DateTimeField(blank=True, null=True)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_quants",
                        to="app.location",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_quants",
                        to="app.product",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="location",
            name="warehouse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="locations",
                to="app.warehouse",
            ),
        ),
    ]
