# Generated by Django 4.2.11 on 2025-05-05 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0032_location_warehouse_stockquant_location_warehouse"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="odoo_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="stockquant",
            name="odoo_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="warehouse",
            name="odoo_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
