# Generated by Django 4.2.11 on 2025-05-05 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0033_alter_location_odoo_id_alter_stockquant_odoo_id_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="productoption",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="option",
            name="additional_price",
        ),
        migrations.RemoveField(
            model_name="variant",
            name="product_templates",
        ),
        migrations.AddField(
            model_name="productoption",
            name="additional_price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=16),
        ),
        migrations.AddField(
            model_name="productoption",
            name="odoo_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="option",
            name="variant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variant_option",
                to="app.variant",
            ),
        ),
        migrations.CreateModel(
            name="ProductVariants",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("odoo_id", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "product_options",
                    models.ManyToManyField(
                        related_name="variant_product_options", to="app.productoption"
                    ),
                ),
                (
                    "product_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_template_options",
                        to="app.producttemplate",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_template_variants",
                        to="app.variant",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="productoption",
            name="product",
        ),
    ]
