# Generated by Django 4.2.11 on 2025-05-06 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0034_alter_productoption_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="odoo_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
