# Generated by Django 4.2.11 on 2025-05-07 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0035_story_odoo_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="aboutus",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="aboutus",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="aboutus",
            name="sync_status",
            field=models.CharField(
                choices=[
                    ("created", "created"),
                    ("updated", "updated"),
                    ("deleted", "deleted"),
                    ("synced", "synced"),
                ],
                default="created",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="appointment",
            name="sync_status",
            field=models.CharField(
                choices=[
                    ("created", "created"),
                    ("updated", "updated"),
                    ("deleted", "deleted"),
                    ("synced", "synced"),
                ],
                default="created",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="appointmentworkingday",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="appointmentworkingday",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="appointmentworkingday",
            name="sync_status",
            field=models.CharField(
                choices=[
                    ("created", "created"),
                    ("updated", "updated"),
                    ("deleted", "deleted"),
                    ("synced", "synced"),
                ],
                default="created",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="appointmentworkingday",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="basket",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="basket",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="basket",
            name="sync_status",
            field=models.CharField(
                choices=[
                    ("created", "created"),
                    ("updated", "updated"),
                    ("deleted", "deleted"),
                    ("synced", "synced"),
                ],
                default="created",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="basket",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="basketitem",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="basketitem",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="basketitem",
            name="sync_status",
            field=models.CharField(
                choices=[
                    ("created", "created"),
                    ("updated", "updated"),
                    ("deleted", "deleted"),
                    ("synced", "synced"),
                ],
                default="created",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="basketitem",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="booking",
            name="sync_status",
            field=models.CharField(
                choices=[
                    ("created", "created"),
                    ("updated", "updated"),
                    ("deleted", "deleted"),
                    ("synced", "synced"),
                ],
                default="created",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="bookingrating",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bookingrating",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="bookingrating",
            name="sync_status",
            field=models.CharField(
                choices=[
                    ("created", "created"),
                    ("updated", "updated"),
                    ("deleted", "deleted"),
                    ("synced", "synced"),
                ],
                default="created",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="bookingrating",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="branch",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="branch",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="branch",
            name="sync_status",
            field=models.CharField(
                choices=[
                    ("created", "created"),
                    ("updated", "updated"),
                    ("deleted", "deleted"),
                    ("synced", "synced"),
                ],
                default="created",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="brand",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="brand",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="brand",
            name="sync_status",
            field=models.CharField(
                choices=[
                    ("created", "created"),
                    ("updated", "updated"),
                    ("deleted", "deleted"),
                    ("synced", "synced"),
                ],
                default="created",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="car",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="car",
            name="sync_status",
            field=models.CharField(
                choices=[
                    ("created", "created"),
                    ("updated", "updated"),
                    ("deleted", "deleted"),
                    ("synced", "synced"),
                ],
                default="created",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="card",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="card",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="card",
            name="sync_status",
            field=models.CharField(
                choices=[
                    ("created", "created"),
                    ("updated", "updated"),
                    ("deleted", "deleted"),
                    ("synced", "synced"),
                ],
                default="created",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="card",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="cardimages",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cardimages",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cardimages",
            name="sync_status",
            field=models.CharField(
                choices=[
                    ("created", "created"),
                    ("updated", "updated"),
                    ("deleted", "deleted"),
                    ("synced", "synced"),
                ],
                default="created",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="cardimages",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="category",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="category",
            name="sync_status",
            field=models.CharField(
                choices=[
                    ("created", "created"),
                    ("updated", "updated"),
                    ("deleted", "deleted"),
                    ("synced", "synced"),
                ],
                default="created",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="check",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="check",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="check",
            name="sync_status",
            field=models.CharField(
                choices=[
                    ("created", "created"),
                    ("updated", "updated"),
                    ("deleted", "deleted"),
                    ("synced", "synced"),
                ],
                default="created",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="check",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="contact",
            name="sync_status",
            field=models.CharField(
                choices=[
                    ("created", "created"),
                    ("updated", "updated"),
                    ("deleted", "deleted"),
                    ("synced", "synced"),
                ],
                default="created",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="discount",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="discount",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="discount",
            name="sync_status",
            field=models.CharField(
                choices=[
                    ("created", "created"),
                    ("updated", "updated"),
                    ("deleted", "deleted"),
                    ("synced", "synced"),
                ],
                default="created",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="discount",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="district",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="district",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="district",
            name="sync_status",
            field=models.CharField(
                choices=[
                    ("created", "created"),
                    ("updated", "updated"),
                    ("deleted", "deleted"),
                    ("synced", "synced"),
                ],
                default="created",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="document",
            name="sync_status",
            field=models.CharField(
                choices=[
                    ("created", "created"),
                    ("updated", "updated"),
                    ("deleted", "deleted"),
                    ("synced", "synced"),
                ],
                default="created",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="faq",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="faq",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="faq",
            name="sync_status",
            field=models.CharField(
                choices=[
                    ("created", "created"),
                    ("updated", "updated"),
                    ("deleted", "deleted"),
                    ("synced", "synced"),
                ],
                default="created",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="invoice",
            name="sync_status",
            field=models.CharField(
                choices=[
                    ("created", "created"),
                    ("updated", "updated"),
                    ("deleted", "deleted"),
                    ("synced", "synced"),
                ],
                default="created",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="location",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="location",
            name="sync_status",
            field=models.CharField(
                choices=[
                    ("created", "created"),
                    ("updated", "updated"),
                    ("deleted", "deleted"),
                    ("synced", "synced"),
                ],
                default="created",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="loyaltycard",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="loyaltycard",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="loyaltycard",
            name="sync_status",
            field=models.CharField(
                choices=[
                    ("created", "created"),
                    ("updated", "updated"),
                    ("deleted", "deleted"),
                    ("synced", "synced"),
                ],
                default="created",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="loyaltycard",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="notification",
            name="sync_status",
            field=models.CharField(
                choices=[
                    ("created", "created"),
                    ("updated", "updated"),
                    ("deleted", "deleted"),
                    ("synced", "synced"),
                ],
                default="created",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="notificationtemplate",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notificationtemplate",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="notificationtemplate",
            name="sync_status",
            field=models.CharField(
                choices=[
                    ("created", "created"),
                    ("updated", "updated"),
                    ("deleted", "deleted"),
                    ("synced", "synced"),
                ],
                default="created",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="offer",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="offer",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="offer",
            name="sync_status",
            field=models.CharField(
                choices=[
                    ("created", "created"),
                    ("updated", "updated"),
                    ("deleted", "deleted"),
                    ("synced", "synced"),
                ],
                default="created",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="option",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="option",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="option",
            name="sync_status",
            field=models.CharField(
                choices=[
                    ("created", "created"),
                    ("updated", "updated"),
                    ("deleted", "deleted"),
                    ("synced", "synced"),
                ],
                default="created",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="option",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="order",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="sync_status",
            field=models.CharField(
                choices=[
                    ("created", "created"),
                    ("updated", "updated"),
                    ("deleted", "deleted"),
                    ("synced", "synced"),
                ],
                default="created",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="sync_status",
            field=models.CharField(
                choices=[
                    ("created", "created"),
                    ("updated", "updated"),
                    ("deleted", "deleted"),
                    ("synced", "synced"),
                ],
                default="created",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="orderrating",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="orderrating",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="orderrating",
            name="sync_status",
            field=models.CharField(
                choices=[
                    ("created", "created"),
                    ("updated", "updated"),
                    ("deleted", "deleted"),
                    ("synced", "synced"),
                ],
                default="created",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="orderrating",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="privacypolicy",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="privacypolicy",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="privacypolicy",
            name="sync_status",
            field=models.CharField(
                choices=[
                    ("created", "created"),
                    ("updated", "updated"),
                    ("deleted", "deleted"),
                    ("synced", "synced"),
                ],
                default="created",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="sync_status",
            field=models.CharField(
                choices=[
                    ("created", "created"),
                    ("updated", "updated"),
                    ("deleted", "deleted"),
                    ("synced", "synced"),
                ],
                default="created",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="productoption",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="productoption",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="productoption",
            name="sync_status",
            field=models.CharField(
                choices=[
                    ("created", "created"),
                    ("updated", "updated"),
                    ("deleted", "deleted"),
                    ("synced", "synced"),
                ],
                default="created",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="productoption",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="productrating",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="productrating",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="productrating",
            name="sync_status",
            field=models.CharField(
                choices=[
                    ("created", "created"),
                    ("updated", "updated"),
                    ("deleted", "deleted"),
                    ("synced", "synced"),
                ],
                default="created",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="productrating",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="producttemplate",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="producttemplate",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="producttemplate",
            name="sync_status",
            field=models.CharField(
                choices=[
                    ("created", "created"),
                    ("updated", "updated"),
                    ("deleted", "deleted"),
                    ("synced", "synced"),
                ],
                default="created",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="productvariants",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="productvariants",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="productvariants",
            name="sync_status",
            field=models.CharField(
                choices=[
                    ("created", "created"),
                    ("updated", "updated"),
                    ("deleted", "deleted"),
                    ("synced", "synced"),
                ],
                default="created",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="productvariants",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="promocode",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="promocode",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="promocode",
            name="sync_status",
            field=models.CharField(
                choices=[
                    ("created", "created"),
                    ("updated", "updated"),
                    ("deleted", "deleted"),
                    ("synced", "synced"),
                ],
                default="created",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="promocode",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="promocodeusage",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="promocodeusage",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="promocodeusage",
            name="sync_status",
            field=models.CharField(
                choices=[
                    ("created", "created"),
                    ("updated", "updated"),
                    ("deleted", "deleted"),
                    ("synced", "synced"),
                ],
                default="created",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="promocodeusage",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="region",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="region",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="region",
            name="sync_status",
            field=models.CharField(
                choices=[
                    ("created", "created"),
                    ("updated", "updated"),
                    ("deleted", "deleted"),
                    ("synced", "synced"),
                ],
                default="created",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="savedproduct",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="savedproduct",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="savedproduct",
            name="sync_status",
            field=models.CharField(
                choices=[
                    ("created", "created"),
                    ("updated", "updated"),
                    ("deleted", "deleted"),
                    ("synced", "synced"),
                ],
                default="created",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="savedproduct",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="stockquant",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stockquant",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="stockquant",
            name="sync_status",
            field=models.CharField(
                choices=[
                    ("created", "created"),
                    ("updated", "updated"),
                    ("deleted", "deleted"),
                    ("synced", "synced"),
                ],
                default="created",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="stockquant",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="story",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="story",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="story",
            name="sync_status",
            field=models.CharField(
                choices=[
                    ("created", "created"),
                    ("updated", "updated"),
                    ("deleted", "deleted"),
                    ("synced", "synced"),
                ],
                default="created",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="story",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="supportcontact",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="supportcontact",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="supportcontact",
            name="sync_status",
            field=models.CharField(
                choices=[
                    ("created", "created"),
                    ("updated", "updated"),
                    ("deleted", "deleted"),
                    ("synced", "synced"),
                ],
                default="created",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="supportcontact",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="useragreement",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="useragreement",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="useragreement",
            name="sync_status",
            field=models.CharField(
                choices=[
                    ("created", "created"),
                    ("updated", "updated"),
                    ("deleted", "deleted"),
                    ("synced", "synced"),
                ],
                default="created",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="variant",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="variant",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="variant",
            name="sync_status",
            field=models.CharField(
                choices=[
                    ("created", "created"),
                    ("updated", "updated"),
                    ("deleted", "deleted"),
                    ("synced", "synced"),
                ],
                default="created",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="variant",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="warehouse",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="warehouse",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="warehouse",
            name="sync_status",
            field=models.CharField(
                choices=[
                    ("created", "created"),
                    ("updated", "updated"),
                    ("deleted", "deleted"),
                    ("synced", "synced"),
                ],
                default="created",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="warehouse",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
