# Generated by Django 4.2.11 on 2025-05-12 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0038_remove_aboutus_is_deleted_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_top",
            field=models.BooleanField(default=False),
        ),
    ]
