# Generated by Django 4.2.11 on 2025-05-12 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0039_product_is_top"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="is_top",
            field=models.BooleanField(default=False),
        ),
    ]
