# Generated by Django 4.2.11 on 2025-05-12 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0040_brand_is_top"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="odoo_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
