# Generated by Django 4.2.11 on 2025-05-12 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0042_aboutus_odoo_id_contact_odoo_id_district_odoo_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
