# Generated by Django 4.2.11 on 2025-05-12 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0043_order_cancelled_at_order_completed_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="completed_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
