# Generated by Django 4.2.11 on 2025-05-12 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0044_alter_order_cancelled_at_alter_order_completed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="branch",
            name="parent_branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.branch",
            ),
        ),
    ]
