# Generated by Django 4.2.11 on 2025-05-13 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0045_branch_parent_branch"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="price",
        ),
        migrations.AddField(
            model_name="product",
            name="attributes",
            field=models.ManyToManyField(to="app.option"),
        ),
        migrations.AddField(
            model_name="productoption",
            name="product_template",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_options",
                to="app.producttemplate",
            ),
            preserve_default=False,
        ),
    ]
