# Generated by Django 4.2.11 on 2025-05-14 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0046_remove_product_price_product_attributes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productoption",
            name="product_template_attribute_line",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_varialts_line",
                to="app.productvariants",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="productvariants",
            name="product_options",
            field=models.ManyToManyField(
                related_name="variant_product_options", to="app.option"
            ),
        ),
    ]
