# Generated by Django 4.2.11 on 2025-05-14 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0047_productoption_product_template_attribute_line_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=16),
        ),
    ]
