# Generated by Django 4.2.11 on 2025-05-15 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0048_product_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="check",
            name="terminal_url",
        ),
        migrations.AddField(
            model_name="check",
            name="terminal_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="name",
            field=models.CharField(default="", max_length=255),
        ),
    ]
