# Generated by Django 4.2.11 on 2025-05-15 11:02

import app.models.product
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0049_remove_check_terminal_url_check_terminal_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=app.models.product.catalog_upload_to
            ),
        ),
    ]
