# Generated by Django 4.2.11 on 2025-05-16 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0050_alter_category_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="location_type",
            field=models.CharField(
                choices=[
                    ("view", "View"),
                    ("internal", "Internal"),
                    ("customer", "Customer"),
                    ("inventory", "Inventory"),
                    ("production", "Production"),
                    ("supplier", "Supplier"),
                    ("transit", "Transit"),
                ],
                max_length=20,
            ),
        ),
    ]
