# Generated by Django 4.2.11 on 2025-05-16 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0051_alter_location_location_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="amount",
            new_name="free_quantity",
        ),
    ]
