# Generated by Django 4.2.11 on 2025-05-19 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0052_rename_amount_product_free_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockquant",
            name="branch",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stock_quants_branch",
                to="app.branch",
            ),
            preserve_default=False,
        ),
    ]
