# Generated by Django 4.2.11 on 2025-05-19 06:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0053_stockquant_branch"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockquant",
            name="in_date",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
