# Generated by Django 4.2.11 on 2025-05-19 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0054_stockquant_in_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="pickup_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
