# Generated by Django 4.2.11 on 2025-05-20 06:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0055_order_pickup_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("odoo_id", models.CharField(blank=True, max_length=255, null=True)),
                ("name", models.CharField(max_length=50)),
                (
                    "code",
                    models.CharField(
                        help_text="ISO 4217 currency code (e.g. USD, EUR)",
                        max_length=3,
                        unique=True,
                    ),
                ),
                ("symbol", models.CharField(max_length=5)),
                (
                    "rounding",
                    models.DecimalField(
                        decimal_places=6,
                        default=0.01,
                        help_text="Rounding factor for this currency (e.g. 0.01 for cents)",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "decimal_places",
                    models.PositiveSmallIntegerField(
                        default=2,
                        help_text="Number of decimal places to display (usually 2)",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Currencies",
                "ordering": ["code"],
            },
        ),
        migrations.AddField(
            model_name="discount",
            name="apply_on",
            field=models.CharField(
                choices=[
                    ("category", "Product Category"),
                    ("template", "Product Template"),
                    ("variant", "Product Variant"),
                    ("all", "All Products"),
                ],
                default="all",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="discount",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="discounts",
                to="app.branch",
            ),
        ),
        migrations.AddField(
            model_name="discount",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="discounts",
                to="app.category",
            ),
        ),
        migrations.AddField(
            model_name="discount",
            name="discount_type",
            field=models.CharField(
                choices=[("percentage", "Percentage"), ("fixed", "Fixed Amount")],
                default="percentage",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="discount",
            name="product_template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="discounts",
                to="app.producttemplate",
            ),
        ),
        migrations.CreateModel(
            name="Pricelist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sync_status",
                    models.CharField(
                        choices=[
                            ("created", "created"),
                            ("updated", "updated"),
                            ("deleted", "deleted"),
                            ("synced", "synced"),
                        ],
                        default="created",
                        max_length=20,
                    ),
                ),
                ("send_odoo", models.BooleanField(default=True)),
                ("odoo_id", models.CharField(blank=True, max_length=255, null=True)),
                ("name", models.CharField(max_length=100)),
                ("active", models.BooleanField(default=True)),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="app.currency"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="discount",
            name="pricelist",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="app.pricelist",
            ),
        ),
    ]
