# Generated by Django 4.2.11 on 2025-05-20 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0056_currency_discount_apply_on_discount_branch_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pricelist",
            name="branch",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pricelists",
                to="app.branch",
            ),
            preserve_default=False,
        ),
    ]
