# Generated by Django 4.2.11 on 2025-05-20 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0058_order_delivery_price_deliveryprice"),
    ]

    operations = [
        migrations.AddField(
            model_name="producttemplate",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="product_templates",
                to="app.branch",
            ),
        ),
    ]
