# Generated by Django 4.2.11 on 2025-05-20 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0059_producttemplate_branch"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discount",
            name="apply_on",
            field=models.CharField(
                choices=[
                    ("category", "Product Category"),
                    ("template", "Product Template"),
                    ("variant", "Product Variant"),
                    ("branch", "Branch"),
                    ("all", "All Products"),
                ],
                default="all",
                max_length=10,
            ),
        ),
    ]
