# Generated by Django 4.2.11 on 2025-05-21 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0060_alter_discount_apply_on"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="promocode",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order",
                to="app.promocode",
            ),
        ),
    ]
