# Generated by Django 4.2.11 on 2025-05-22 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0062_alter_aboutus_sync_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OilBrand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sync_status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("updated", "Updated"),
                            ("deleted", "Deleted"),
                            ("synced", "Synced"),
                        ],
                        default="created",
                        max_length=20,
                    ),
                ),
                ("send_odoo", models.BooleanField(default=True)),
                ("odoo_id", models.CharField(blank=True, max_length=255, null=True)),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
