# Generated by Django 4.2.11 on 2025-05-23 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0063_oilbrand"),
    ]

    operations = [
        migrations.CreateModel(
            name="Balance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("odoo_id", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "sync_status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("updated", "Updated"),
                            ("deleted", "Deleted"),
                            ("synced", "Synced"),
                        ],
                        default="created",
                        max_length=20,
                    ),
                ),
                ("send_odoo", models.BooleanField(default=True)),
                ("unique_id", models.CharField(max_length=255)),
                ("balance", models.DecimalField(decimal_places=2, max_digits=16)),
                ("total_sales", models.DecimalField(decimal_places=2, max_digits=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BalanceStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("odoo_id", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "sync_status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("updated", "Updated"),
                            ("deleted", "Deleted"),
                            ("synced", "Synced"),
                        ],
                        default="created",
                        max_length=20,
                    ),
                ),
                ("send_odoo", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("percentage", models.DecimalField(decimal_places=2, max_digits=16)),
                (
                    "minimum_amount",
                    models.DecimalField(decimal_places=2, max_digits=16),
                ),
                (
                    "next_minimum_amount",
                    models.DecimalField(decimal_places=2, max_digits=16),
                ),
                ("num", models.IntegerField()),
                (
                    "time_line",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DAYS", "Days"),
                            ("WEEKS", "Weeks"),
                            ("MONTHS", "Months"),
                            ("YEARS", "Years"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                ("description_uz", models.TextField(blank=True, null=True)),
                ("description_ru", models.TextField(blank=True, null=True)),
                ("description_en", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Cashback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("odoo_id", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "sync_status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("updated", "Updated"),
                            ("deleted", "Deleted"),
                            ("synced", "Synced"),
                        ],
                        default="created",
                        max_length=20,
                    ),
                ),
                ("send_odoo", models.BooleanField(default=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, help_text="The amount of order", max_digits=16
                    ),
                ),
                ("status", models.CharField(max_length=255)),
                ("percentage", models.DecimalField(decimal_places=2, max_digits=16)),
                ("cashback", models.DecimalField(decimal_places=2, max_digits=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "balance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cashbacks",
                        to="app.balance",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cashbacks",
                        to="app.order",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="balance",
            name="balance_status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="balances",
                to="app.balancestatus",
            ),
        ),
        migrations.AddField(
            model_name="balance",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="balances",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
