# Generated by Django 4.2.11 on 2025-05-23 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0064_balance_balancestatus_cashback_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cashback",
            name="status",
        ),
        migrations.AddField(
            model_name="cashback",
            name="state",
            field=models.CharField(
                blank=True,
                choices=[
                    ("given", "Given"),
                    ("reversed", "Reversed"),
                    ("used", "Used"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="balancestatus",
            name="time_line",
            field=models.CharField(
                blank=True,
                choices=[
                    ("day", "Days"),
                    ("week", "Weeks"),
                    ("month", "Months"),
                    ("year", "Years"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
