# Generated by Django 4.2.11 on 2025-05-23 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0065_remove_cashback_status_cashback_state_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="balancestatus",
            name="icon",
            field=models.ImageField(blank=True, null=True, upload_to="balance_status/"),
        ),
    ]
