# Generated by Django 4.2.11 on 2025-05-23 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0066_balancestatus_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
