# Generated by Django 4.2.11 on 2025-05-23 16:37

import app.models.company_info
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0067_order_updated_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyBenefit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=app.models.company_info.company_benefit_upload_to,
                    ),
                ),
                ("title_en", models.CharField(blank=True, max_length=255)),
                ("title_ru", models.CharField(blank=True, max_length=255)),
                ("title_uz", models.CharField(blank=True, max_length=255)),
                ("description_en", models.TextField(blank=True)),
                ("description_ru", models.TextField(blank=True)),
                ("description_uz", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "CompanyBenefit",
                "verbose_name_plural": "CompanyBenefit",
            },
        ),
        migrations.CreateModel(
            name="CompanyComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=255)),
                (
                    "company_logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=app.models.company_info.company_logo_upload_to,
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=app.models.company_info.comment_avatar_upload_to,
                    ),
                ),
                ("full_name_en", models.CharField(max_length=255)),
                ("full_name_uz", models.CharField(max_length=255)),
                ("full_name_ru", models.CharField(max_length=255)),
                ("comment_en", models.TextField(blank=True)),
                ("comment_uz", models.TextField(blank=True)),
                ("comment_ru", models.TextField(blank=True)),
                ("position_en", models.CharField(max_length=100)),
                ("position_uz", models.CharField(max_length=100)),
                ("position_ru", models.CharField(max_length=100)),
            ],
        ),
    ]
