# Generated by Django 4.2.11 on 2025-05-24 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0068_companybenefit_companycomment"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="mxik",
            field=models.CharField(default=11201001001000000, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="category",
            name="package_code",
            field=models.CharField(default=1500729, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="mxik",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="package_code",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
