# Generated by Django 4.2.11 on 2025-05-24 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0069_category_mxik_category_package_code_product_mxik_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="raxmat_reference",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="uuid",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
