# Generated by Django 4.2.11 on 2025-05-24 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0070_order_raxmat_reference_alter_order_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderrating",
            name="rating_type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
