# Generated by Django 5.2 on 2025-05-24 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0071_orderrating_rating_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sync_status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("updated", "Updated"),
                            ("deleted", "Deleted"),
                            ("synced", "Synced"),
                        ],
                        default="created",
                        max_length=20,
                    ),
                ),
                ("send_odoo", models.BooleanField(default=True)),
                ("odoo_id", models.CharField(blank=True, max_length=255, null=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.AlterModelOptions(
            name="appointment",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="appointmentworkingday",
            options={"ordering": ["id"]},
        ),
        migrations.AlterUniqueTogether(
            name="appointmentworkingday",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="slot_capacity",
        ),
        migrations.AlterField(
            model_name="appointment",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointment",
                to="app.branch",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="resources",
            field=models.ManyToManyField(
                blank=True, related_name="appointments", to="app.resource"
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="resource",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to="app.resource",
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("status__in", ["CONFIRMED", "PENDING"]),
                    ("resource__isnull", False),
                ),
                fields=("appointment", "start_time", "resource"),
                name="unique_resource_booking_per_appointment_slot",
            ),
        ),
        migrations.RemoveField(
            model_name="appointmentworkingday",
            name="is_open",
        ),
        migrations.RemoveField(
            model_name="appointmentworkingday",
            name="lunch_end",
        ),
        migrations.RemoveField(
            model_name="appointmentworkingday",
            name="lunch_start",
        ),
    ]
