# Generated by Django 4.2.11 on 2025-05-24 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0073_alter_invoice_booking_alter_invoice_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="SomeColor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("odoo_id", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "sync_status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("updated", "Updated"),
                            ("deleted", "Deleted"),
                            ("synced", "Synced"),
                        ],
                        default="created",
                        max_length=20,
                    ),
                ),
                ("send_odoo", models.BooleanField(default=True)),
                ("name_en", models.CharField(max_length=255)),
                ("name_uz", models.CharField(max_length=255)),
                ("name_ru", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="carmodel",
            name="send_odoo",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="carmodel",
            name="sync_status",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("updated", "Updated"),
                    ("deleted", "Deleted"),
                    ("synced", "Synced"),
                ],
                default="created",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="firm",
            name="send_odoo",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="firm",
            name="sync_status",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("updated", "Updated"),
                    ("deleted", "Deleted"),
                    ("synced", "Synced"),
                ],
                default="created",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="oilchangedhistory",
            name="send_odoo",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="oilchangedhistory",
            name="sync_status",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("updated", "Updated"),
                    ("deleted", "Deleted"),
                    ("synced", "Synced"),
                ],
                default="created",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="CarColor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("odoo_id", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "sync_status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("updated", "Updated"),
                            ("deleted", "Deleted"),
                            ("synced", "Synced"),
                        ],
                        default="created",
                        max_length=20,
                    ),
                ),
                ("send_odoo", models.BooleanField(default=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="car_colors/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "car_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="car_colors",
                        to="app.carmodel",
                    ),
                ),
                (
                    "some_color",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="car_colors",
                        to="app.somecolor",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="car",
            name="color",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cars",
                to="app.carcolor",
            ),
        ),
    ]
