# Generated by Django 4.2.11 on 2025-05-24 14:05

import app.models.booking
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0074_somecolor_carmodel_send_odoo_carmodel_sync_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="name",
            field=models.CharField(
                default=app.models.booking.generate_unique_booking_name,
                max_length=6,
                unique=True,
            ),
        ),
    ]
