# Generated by Django 4.2.11 on 2025-05-25 08:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0075_booking_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="f_num",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="fiscal_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="fm_num",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="raxmat_payment_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="uuid",
            field=models.UUIDField(
                blank=True, default=uuid.uuid4, editable=False, null=True, unique=True
            ),
        ),
        migrations.DeleteModel(
            name="Check",
        ),
    ]
