# Generated by Django 4.2.11 on 2025-05-25 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0076_order_f_num_order_fiscal_url_order_fm_num_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_time",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
