# Generated by Django 4.2.11 on 2025-05-25 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0077_order_payment_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="oilchangedhistory",
            name="duration_days",
            field=models.PositiveIntegerField(
                default=1, help_text="Duration of oil change (in days)"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="oilchangedhistory",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="oil_change_history",
                to="app.order",
            ),
        ),
        migrations.AlterField(
            model_name="oilchangedhistory",
            name="oil_brand",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="oil_change_history",
                to="app.oilbrand",
            ),
        ),
    ]
