# Generated by Django 4.2.11 on 2025-05-25 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0078_oilchangedhistory_duration_days_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="color",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cars",
                to="app.carcolor",
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="firm",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cars",
                to="app.firm",
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="model",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cars",
                to="app.carmodel",
            ),
        ),
    ]
