# Generated by Django 4.2.11 on 2025-05-25 16:29

import app.models.product
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0079_alter_car_color_alter_car_firm_alter_car_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="attributes",
            field=models.ManyToManyField(blank=True, to="app.option"),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                default="default_image.jpg",
                null=True,
                upload_to=app.models.product.product_upload_to,
            ),
        ),
    ]
