# Generated by Django 4.2.11 on 2025-05-26 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0080_alter_product_attributes_alter_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="oilchangedhistory",
            name="duration_days",
            field=models.PositiveIntegerField(
                blank=True, help_text="Duration of oil change (in days)", null=True
            ),
        ),
    ]
