# Generated by Django 4.2.11 on 2025-05-26 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0081_alter_oilchangedhistory_duration_days"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="branch_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="brach_locations",
                to="app.branch",
            ),
        ),
    ]
