# Generated by Django 4.2.11 on 2025-05-26 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0017_remove_address_address_address_additional"),
        ("app", "0082_location_branch_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="address",
        ),
        migrations.AddField(
            model_name="order",
            name="address_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="user.address",
            ),
        ),
    ]
