# Generated by Django 4.2.11 on 2025-05-26 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0083_remove_order_address_order_address_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderrating",
            name="rating",
            field=models.FloatField(),
        ),
    ]
