# Generated by Django 4.2.11 on 2025-05-26 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0084_alter_orderrating_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CASH", "Cash"),
                    ("CLICK", "Click"),
                    ("CARD", "Card"),
                    ("PAYME", "Payme"),
                    ("UZUM", "Uzum"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
