# Generated by Django 4.2.11 on 2025-05-27 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0085_alter_order_payment_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="branch",
            name="order_expiration_days",
            field=models.PositiveIntegerField(
                blank=True, help_text="Order expiration time (in days)", null=True
            ),
        ),
    ]
