# Generated by Django 4.2.11 on 2025-05-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0086_branch_order_expiration_days"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("CASH", "Cash"),
                    ("CLICK", "Click"),
                    ("CARD", "Card"),
                    ("PAYME", "Payme"),
                    ("UZUM", "Uzum"),
                ],
                default="CARD",
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
