# Generated by Django 4.2.11 on 2025-05-28 10:01

import app.models.product
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0087_alter_order_payment_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Product description (If empty, the product template description will be used)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Product image (If empty, the product template image will be used)",
                null=True,
                upload_to=app.models.product.product_upload_to,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
