# Generated by Django 4.2.11 on 2025-05-29 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0088_alter_product_description_alter_product_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="number",
            field=models.CharField(
                help_text="License plate or car number (Uzbekistan)",
                max_length=20,
                unique=True,
            ),
        ),
    ]
