# Generated by Django 4.2.11 on 2025-05-29 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0089_alter_car_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingrating",
            name="rating_type",
            field=models.CharField(
                choices=[("GOOD", "Good"), ("AVERAGE", "Average"), ("BAD", "Bad")],
                default="AVERAGE",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="bookingrating",
            name="rating",
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
