# Generated by Django 4.2.11 on 2025-05-31 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0090_bookingrating_rating_type_alter_bookingrating_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliveryprice",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("CASH", "Cash"),
                    ("CLICK", "Click"),
                    ("CARD", "Card"),
                    ("PAYME", "Payme"),
                    ("UZUM", "Uzum"),
                    ("ON_RECEIVE", "On Receive"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
    ]
