# Generated by Django 4.2.11 on 2025-05-31 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0091_alter_deliveryprice_price_alter_order_payment_method_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basket",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name="basketitem",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name="basketitem",
            name="total_price",
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
    ]
