# Generated by Django 4.2.11 on 2025-05-31 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0092_alter_basket_price_alter_basketitem_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aboutus",
            name="odoo_id",
            field=models.CharField(
                default="01a95d87-5b82-42f0-9a18-cfacb62826a1", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="balance",
            name="odoo_id",
            field=models.CharField(
                default="01a95d87-5b82-42f0-9a18-cfacb62826a1", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="balancestatus",
            name="odoo_id",
            field=models.CharField(
                default="01a95d87-5b82-42f0-9a18-cfacb62826a1", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="odoo_id",
            field=models.CharField(
                default="01a95d87-5b82-42f0-9a18-cfacb62826a1", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="carcolor",
            name="odoo_id",
            field=models.CharField(
                default="01a95d87-5b82-42f0-9a18-cfacb62826a1", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="carmodel",
            name="odoo_id",
            field=models.CharField(
                default="01a95d87-5b82-42f0-9a18-cfacb62826a1", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="cashback",
            name="odoo_id",
            field=models.CharField(
                default="01a95d87-5b82-42f0-9a18-cfacb62826a1", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="odoo_id",
            field=models.CharField(
                default="01a95d87-5b82-42f0-9a18-cfacb62826a1", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="deliveryprice",
            name="odoo_id",
            field=models.CharField(
                default="01a95d87-5b82-42f0-9a18-cfacb62826a1", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="district",
            name="odoo_id",
            field=models.CharField(
                default="01a95d87-5b82-42f0-9a18-cfacb62826a1", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="odoo_id",
            field=models.CharField(
                default="01a95d87-5b82-42f0-9a18-cfacb62826a1", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="faq",
            name="odoo_id",
            field=models.CharField(
                default="01a95d87-5b82-42f0-9a18-cfacb62826a1", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="firm",
            name="odoo_id",
            field=models.CharField(
                default="01a95d87-5b82-42f0-9a18-cfacb62826a1", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="privacypolicy",
            name="odoo_id",
            field=models.CharField(
                default="01a95d87-5b82-42f0-9a18-cfacb62826a1", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="promocodeusage",
            name="odoo_id",
            field=models.CharField(
                default="01a95d87-5b82-42f0-9a18-cfacb62826a1", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="region",
            name="odoo_id",
            field=models.CharField(
                default="01a95d87-5b82-42f0-9a18-cfacb62826a1", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="somecolor",
            name="odoo_id",
            field=models.CharField(
                default="01a95d87-5b82-42f0-9a18-cfacb62826a1", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="supportcontact",
            name="odoo_id",
            field=models.CharField(
                default="01a95d87-5b82-42f0-9a18-cfacb62826a1", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="useragreement",
            name="odoo_id",
            field=models.CharField(
                default="01a95d87-5b82-42f0-9a18-cfacb62826a1", max_length=255
            ),
        ),
    ]
