# Generated by Django 5.2 on 2025-06-03 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0094_alter_aboutus_odoo_id_alter_balance_odoo_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="discount",
        ),
        migrations.AddField(
            model_name="order",
            name="pricelist",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order",
                to="app.pricelist",
            ),
        ),
    ]
