# Generated by Django 5.2 on 2025-06-03 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0095_remove_order_discount_order_pricelist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discount",
            name="quantity",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="discount",
            name="time_from",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="discount",
            name="time_to",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
