# Generated by Django 5.2 on 2025-06-03 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0096_alter_discount_quantity_alter_discount_time_from_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pricelist",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pricelists",
                to="app.branch",
            ),
        ),
    ]
