# Generated by Django 5.2 on 2025-06-04 12:01

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0097_alter_pricelist_branch"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="offer",
            name="products",
        ),
        migrations.AddField(
            model_name="offer",
            name="description_en",
            field=ckeditor.fields.RichTextField(
                blank=True, help_text="Offer description in English", null=True
            ),
        ),
        migrations.AddField(
            model_name="offer",
            name="description_ru",
            field=ckeditor.fields.RichTextField(
                blank=True, help_text="Offer description in Russian", null=True
            ),
        ),
        migrations.AddField(
            model_name="offer",
            name="description_uz",
            field=ckeditor.fields.RichTextField(
                blank=True, help_text="Offer description in Uzbek", null=True
            ),
        ),
    ]
