# Generated by Django 5.2 on 2025-06-05 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0098_remove_offer_products_offer_description_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="car",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="app.car",
            ),
        ),
    ]
