# Generated by Django 4.2.11 on 2025-06-05 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0099_order_car"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("CASH", "Cash"),
                    ("CLICK", "Click"),
                    ("CARD", "Card"),
                    ("PAYME", "Payme"),
                    ("UZUM", "Uzum"),
                    ("MULTICARD", "Multicard"),
                    ("XAZNA", "Xazna"),
                    ("ALIF", "Alif"),
                    ("BEEPUL", "Beepul"),
                    ("ANORBANK", "Anorbank"),
                    ("OSON", "Oson"),
                    ("ON_RECEIVE", "On Receive"),
                ],
                max_length=20,
            ),
        ),
    ]
