# Generated by Django 4.2.11 on 2025-06-05 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0100_alter_order_payment_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="oilchangedhistory",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="oil_change_history",
                to="app.branch",
            ),
        ),
    ]
