# Generated by Django 4.2.11 on 2025-06-09 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0101_oilchangedhistory_branch"),
    ]

    operations = [
        migrations.CreateModel(
            name="FilterBrand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("odoo_id", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "sync_status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("updated", "Updated"),
                            ("deleted", "Deleted"),
                            ("synced", "Synced"),
                        ],
                        default="created",
                        max_length=20,
                    ),
                ),
                ("send_odoo", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="oilchangedhistory",
            name="filter_changed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="oilchangedhistory",
            name="note",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="oilchangedhistory",
            name="filter_brand",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="oil_change_history",
                to="app.filterbrand",
            ),
        ),
    ]
