# Generated by Django 4.2.11 on 2025-06-09 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0102_filterbrand_oilchangedhistory_filter_changed_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filterbrand",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
