# Generated by Django 5.2 on 2025-06-09 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0103_alter_filterbrand_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebPageInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title_en", models.CharField(blank=True, max_length=255, null=True)),
                ("title_ru", models.CharField(blank=True, max_length=255, null=True)),
                ("title_uz", models.CharField(blank=True, max_length=255, null=True)),
                ("url_uz", models.URLField(blank=True, null=True)),
                ("url_ru", models.URLField(blank=True, null=True)),
                ("url_en", models.URLField(blank=True, null=True)),
            ],
        ),
    ]
