# Generated by Django 4.2.11 on 2025-06-09 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0104_webpageinfo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="filterbrand",
            name="description",
        ),
    ]
