# Generated by Django 4.2.11 on 2025-06-09 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0105_remove_filterbrand_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="oilchangedhistory",
            name="last_oil_change",
            field=models.DateTimeField(),
        ),
    ]
