# Generated by Django 5.2 on 2025-06-09 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0106_alter_oilchangedhistory_last_oil_change"),
    ]

    operations = [
        migrations.CreateModel(
            name="BalanceUsageLimit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "min_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=16),
                ),
                (
                    "max_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=16),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="order",
            name="balance_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("CASH", "Cash"),
                    ("CLICK", "Click"),
                    ("CARD", "Card"),
                    ("PAYME", "Payme"),
                    ("UZUM", "Uzum"),
                    ("MULTICARD", "Multicard"),
                    ("XAZNA", "Xazna"),
                    ("ALIF", "Alif"),
                    ("BEEPUL", "Beepul"),
                    ("ANORBANK", "Anorbank"),
                    ("OSON", "Oson"),
                    ("ON_RECEIVE", "On Receive"),
                    ("CASHBACK", "Cashback"),
                    ("MIXED", "Mixed"),
                ],
                max_length=20,
            ),
        ),
    ]
