# Generated by Django 5.2 on 2025-06-09 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0107_balanceusagelimit_order_balance_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="url",
            field=models.URLField(
                blank=True,
                help_text="Product URL on website",
                max_length=500,
                null=True,
            ),
        ),
    ]
