# Generated by Django 4.2.11 on 2025-06-10 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0108_product_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="branch",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="branch_locations",  # Corrected typo
                to="app.branch",
                db_column="branch_id",  # Reuse existing branch_id column
            ),
        ),
        migrations.AlterField(
            model_name="stockquant",
            name="quantity",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="stockquant",
            name="reserved_quantity",
            field=models.IntegerField(default=0),
        ),
    ]
