# Generated by Django 4.2.11 on 2025-06-10 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0109_remove_location_branch_id_location_branch_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="location",
            name="branch_id",
        ),
        migrations.AlterField(
            model_name="location",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="brach_locations",
                to="app.branch",
            ),
        ),
    ]
