# Generated by Django 4.2.11 on 2025-06-10 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0110_remove_location_branch_id_alter_location_branch"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="branch_locations",
                to="app.branch",
            ),
        ),
    ]
