# Generated by Django 4.2.11 on 2025-06-11 07:45

import app.models.order
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0111_alter_location_branch"),
    ]

    operations = [
        migrations.CreateModel(
            name="RatingType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("odoo_id", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "sync_status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("updated", "Updated"),
                            ("deleted", "Deleted"),
                            ("synced", "Synced"),
                        ],
                        default="created",
                        max_length=20,
                    ),
                ),
                ("send_odoo", models.BooleanField(default=True)),
                (
                    "icon",
                    models.FileField(upload_to=app.models.order.rating_image_file_path),
                ),
                ("name_en", models.CharField()),
                ("name_ru", models.CharField()),
                ("name_uz", models.CharField()),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[("bad", "Bad"), ("good", "Good")],
                        default="good",
                        max_length=255,
                        null=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="orderrating",
            name="rating_type",
        ),
        migrations.AlterField(
            model_name="orderrating",
            name="rating",
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name="OilChangeRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sync_status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("updated", "Updated"),
                            ("deleted", "Deleted"),
                            ("synced", "Synced"),
                        ],
                        default="created",
                        max_length=20,
                    ),
                ),
                ("send_odoo", models.BooleanField(default=True)),
                ("odoo_id", models.CharField(blank=True, max_length=255, null=True)),
                ("rating", models.IntegerField()),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "oil_change_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="app.oilchangedhistory",
                    ),
                ),
                (
                    "options_ids",
                    models.ManyToManyField(
                        related_name="oil_change_options", to="app.ratingtype"
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oil_change_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="orderrating",
            name="options_ids",
            field=models.ManyToManyField(
                related_name="order_options", to="app.ratingtype"
            ),
        ),
    ]
