# Generated by Django 5.2 on 2025-06-11 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0112_ratingtype_remove_orderrating_rating_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="basketitem",
            name="discount_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Discount amount applied to this item",
                max_digits=14,
            ),
        ),
        migrations.AddField(
            model_name="basketitem",
            name="discount_percent",
            field=models.FloatField(
                default=0.0, help_text="Discount percentage applied to this item"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="balance_status_name",
            field=models.CharField(
                blank=True,
                help_text="Name of the balance status at order creation",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="discount_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Discount amount applied to this item",
                max_digits=14,
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="discount_percent",
            field=models.FloatField(
                default=0.0, help_text="Discount percentage applied to this item"
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="total_price",
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
    ]
