# Generated by Django 5.2 on 2025-06-11 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0113_basketitem_discount_amount_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="savedproduct",
            name="product",
        ),
        migrations.AddField(
            model_name="savedproduct",
            name="product_template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="saved_products",
                to="app.producttemplate",
            ),
        ),
    ]
