# Generated by Django 4.2.11 on 2025-06-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0114_remove_savedproduct_product_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="promocode_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Promocode amount applied to this order",
                max_digits=14,
            ),
        ),
    ]
