# Generated by Django 5.2 on 2025-06-12 06:46

import app.models.product
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0115_order_promocode_amount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="producttemplate",
            name="image",
        ),
        migrations.CreateModel(
            name="ProductTemplateImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=app.models.product.product_template_upload_to,
                    ),
                ),
                (
                    "product_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="app.producttemplate",
                    ),
                ),
            ],
        ),
    ]
