# Generated by Django 5.2 on 2025-06-12 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0116_remove_producttemplate_image_producttemplateimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="producttemplateimage",
            name="odoo_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="producttemplateimage",
            name="send_odoo",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="producttemplateimage",
            name="sync_status",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("updated", "Updated"),
                    ("deleted", "Deleted"),
                    ("synced", "Synced"),
                ],
                default="created",
                max_length=20,
            ),
        ),
    ]
