# Generated by Django 5.2 on 2025-06-12 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0117_producttemplateimage_odoo_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="url",
        ),
        migrations.AddField(
            model_name="producttemplate",
            name="url",
            field=models.URLField(
                blank=True,
                help_text="Product URL on website",
                max_length=500,
                null=True,
            ),
        ),
    ]
