# Generated by Django 4.2.11 on 2025-06-12 14:48

import django.core.serializers.json
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0118_remove_product_url_producttemplate_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="OdooConnectorLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "operation_type",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("read", "Read"),
                        ],
                        max_length=10,
                    ),
                ),
                ("model_name", models.CharField(max_length=255)),
                ("local_model", models.CharField(max_length=255)),
                ("instance_id", models.IntegerField()),
                ("odoo_id", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("retrying", "Retrying"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("retry_count", models.IntegerField(default=0)),
                ("last_retry", models.DateTimeField(blank=True, null=True)),
                (
                    "request_data",
                    models.JSONField(
                        blank=True,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                    ),
                ),
                (
                    "response_data",
                    models.JSONField(
                        blank=True,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("stack_trace", models.TextField(blank=True, null=True)),
                (
                    "duration",
                    models.FloatField(
                        blank=True, help_text="Operation duration in seconds", null=True
                    ),
                ),
                (
                    "request_size",
                    models.IntegerField(
                        blank=True, help_text="Request size in bytes", null=True
                    ),
                ),
                (
                    "response_size",
                    models.IntegerField(
                        blank=True, help_text="Response size in bytes", null=True
                    ),
                ),
                (
                    "correlation_id",
                    models.UUIDField(blank=True, null=True, unique=True),
                ),
                (
                    "initiated_by",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("batch_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Odoo Connector Log",
                "verbose_name_plural": "Odoo Connector Logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["model_name", "operation_type"],
                        name="app_odoocon_model_n_5c2c14_idx",
                    ),
                    models.Index(
                        fields=["status", "timestamp"],
                        name="app_odoocon_status_fe89f8_idx",
                    ),
                    models.Index(
                        fields=["odoo_id"], name="app_odoocon_odoo_id_721fee_idx"
                    ),
                    models.Index(
                        fields=["correlation_id"], name="app_odoocon_correla_53b398_idx"
                    ),
                ],
            },
        ),
    ]
