# Generated by Django 5.2 on 2025-06-13 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0119_odooconnectorlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="productrating",
            name="anonimous",
            field=models.BooleanField(
                default=False, help_text="If True, the review will be anonymous"
            ),
        ),
    ]
