# Generated by Django 4.2.11 on 2025-06-13 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0120_productrating_anonimous"),
    ]

    operations = [
        migrations.AlterField(
            model_name="odooconnectorlog",
            name="instance_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
