# Generated by Django 4.2.11 on 2025-06-13 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0121_alter_odooconnectorlog_instance_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productrating",
            old_name="anonimous",
            new_name="anonymous",
        ),
    ]
