# Generated by Django 4.2.11 on 2025-06-13 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0122_rename_anonimous_productrating_anonymous'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='name_ru',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='name_uz',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='balancestatus',
            name='next_minimum_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='balancestatus',
            name='num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
