# Generated by Django 4.2.11 on 2025-06-14 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0123_branch_name_ru_branch_name_uz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='source',
            field=models.CharField(choices=[('WEB', 'Web'), ('MOBILE', 'Mobile'), ('TG_MINI_APP', 'Telegram Mini App')], default='WEB', max_length=20),
        ),
    ]
