# Generated by Django 4.2.11 on 2025-06-16 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0124_order_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='recrutement',
            field=models.URLField(blank=True, null=True),
        ),
    ]
