# Generated by Django 5.2 on 2025-06-17 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0125_contact_recrutement"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="is_visible",
            field=models.BooleanField(
                default=True, help_text="Is this category visible on the website?"
            ),
        ),
    ]
