# Generated by Django 4.2.11 on 2025-06-17 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0126_category_is_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='somecolor',
            name='color_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
