# Generated by Django 4.2.11 on 2025-06-18 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0127_somecolor_color_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttemplate',
            name='is_top',
            field=models.BooleanField(default=False, help_text='Is this product top rated?'),
        ),
    ]
