# Generated by Django 4.2.11 on 2025-06-18 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0128_producttemplate_is_top'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttemplate',
            name='is_visible',
            field=models.BooleanField(default=False),
        ),
    ]
