# Generated by Django 4.2.11 on 2025-06-19 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0130_alter_producttemplate_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='balance_percentage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
