# Generated by Django 5.2 on 2025-06-19 09:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0131_order_balance_percentage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="booking",
            name="unique_user_booking_per_appointment_slot",
        ),
        migrations.RemoveConstraint(
            model_name="booking",
            name="unique_car_booking_per_appointment_slot",
        ),
        migrations.RemoveConstraint(
            model_name="booking",
            name="unique_resource_booking_per_appointment_slot",
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("status__in", ["CONFIRMED", "PENDING"]), ("car__isnull", True)
                ),
                fields=("appointment", "start_time", "user"),
                name="unique_user_booking_without_car_per_slot",
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("status__in", ["CONFIRMED", "PENDING"]), ("car__isnull", False)
                ),
                fields=("appointment", "start_time", "car"),
                name="unique_car_booking_per_slot",
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("status__in", ["CONFIRMED", "PENDING"]),
                    ("resource__isnull", False),
                ),
                fields=("appointment", "start_time", "resource"),
                name="unique_resource_booking_per_slot",
            ),
        ),
    ]
