# Generated by Django 4.2.11 on 2025-06-19 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0132_remove_booking_unique_user_booking_per_appointment_slot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='balance_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
        migrations.AddField(
            model_name='invoice',
            name='f_num',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='fiscal_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='fm_num',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='CheckForUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_number', models.IntegerField()),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_type', models.CharField(blank=True, null=True)),
                ('fiscal_url', models.CharField(blank=True, max_length=255, null=True)),
                ('f_num', models.CharField(blank=True, max_length=255, null=True)),
                ('fm_num', models.CharField(blank=True, max_length=255, null=True)),
                ('balance_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('given_cashback', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=16, null=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_check', to='app.order')),
                ('products', models.ManyToManyField(related_name='products_for_check', to='app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_check', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
