# Generated by Django 5.2 on 2025-06-19 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0133_invoice_balance_amount_invoice_f_num_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="branch",
            name="is_main",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if this branch is the main branch of the company",
            ),
        ),
    ]
