# Generated by Django 5.2 on 2025-06-20 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0135_branch_city_branch_phone_branch_street_order_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="balance_percentage",
            field=models.IntegerField(default=0),
        ),
    ]
