# Generated by Django 4.2.11 on 2025-06-20 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0136_alter_order_balance_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='vat',
            field=models.CharField(default='310516499', max_length=50),
        ),
    ]
