# Generated by Django 4.2.11 on 2025-06-21 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0137_branch_vat'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='card_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
        migrations.AddField(
            model_name='order',
            name='cash_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
        migrations.AddField(
            model_name='order',
            name='order_reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
