# Generated by Django 5.2 on 2025-06-24 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0138_order_card_amount_order_cash_amount_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="discount",
            name="apply_on",
        ),
    ]
