# Generated by Django 4.2.11 on 2025-06-24 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0139_remove_discount_apply_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='unique_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
