# Generated by Django 5.2 on 2025-06-26 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0142_order_discount_amount_order_total_price"),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="context",
            field=models.JSONField(
                blank=True,
                help_text="Additional context like days_until_expiration or booking details",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                default="general",
                help_text="Type of notification (e.g., oil_change_reminder, booking_confirmation)",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="object_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.UniqueConstraint(
                fields=("content_type", "object_id", "notification_type", "context"),
                name="unique_notification",
            ),
        ),
    ]
