# Generated by Django 4.2.11 on 2025-06-26 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0143_notification_content_type_notification_context_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odoo_id', models.CharField(blank=True, max_length=255, null=True)),
                ('sync_status', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('synced', 'Synced')], default='created', max_length=20)),
                ('send_odoo', models.BooleanField(default=True)),
                ('name', models.CharField(default='No name', max_length=255)),
                ('program_type', models.CharField(choices=[('coupons', 'Coupons')], max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('limit_usage', models.BooleanField(default=False)),
                ('max_usage', models.PositiveIntegerField(default=0)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loyalty_programs', to='app.branch')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loyalty_programs', to='app.currency')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='promocode',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='promocode',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='promocode',
            name='max_amount',
        ),
        migrations.RemoveField(
            model_name='promocode',
            name='max_usage_per_user',
        ),
        migrations.RemoveField(
            model_name='promocode',
            name='min_amount',
        ),
        migrations.RemoveField(
            model_name='promocode',
            name='percent',
        ),
        migrations.RemoveField(
            model_name='promocode',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='promocode',
            name='send_odoo',
        ),
        migrations.RemoveField(
            model_name='promocode',
            name='sync_status',
        ),
        migrations.RemoveField(
            model_name='promocode',
            name='time_from',
        ),
        migrations.RemoveField(
            model_name='promocode',
            name='time_to',
        ),
        migrations.RemoveField(
            model_name='promocode',
            name='user_by_users',
        ),
        migrations.RemoveField(
            model_name='promocode',
            name='users',
        ),
        migrations.AddField(
            model_name='promocode',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='promocode',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='promocode',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='promocode',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='odoo_id',
            field=models.CharField(default='default-odoo-id-for-migratons', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PromoReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odoo_id', models.CharField(blank=True, max_length=255, null=True)),
                ('sync_status', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('synced', 'Synced')], default='created', max_length=20)),
                ('send_odoo', models.BooleanField(default=True)),
                ('reward_type', models.CharField(choices=[('discount', 'Discount')], default='discount', max_length=20)),
                ('discount', models.FloatField(default=0.0)),
                ('discount_applicability', models.CharField(choices=[('order', 'Order'), ('cheapest', 'Cheapest'), ('specific', 'Specific')], default='order', max_length=20)),
                ('discount_max_amount', models.FloatField(default=0.0)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('discount_line_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promocode_rewards', to='app.product')),
                ('discount_product_category_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promocode_rewards', to='app.category')),
                ('discount_product_ids', models.ManyToManyField(blank=True, related_name='promocode_rewards_many', to='app.product')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promocode_rewards', to='app.loyaltyprogram')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='promocode',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promocodes', to='app.loyaltyprogram'),
        ),
    ]
