# Generated by Django 4.2.11 on 2025-06-26 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0144_loyaltyprogram_remove_promocode_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('CASHBACK', 'Cashback'), ('PRODUCT', 'Product'), ('DELIVERY_PRICE', 'Delivery Price'), ('CUPON', 'Failed')], default='PRODUCT', help_text='Type of product (e.g., cashback, product, delivery price, coupon)', max_length=20),
        ),
        migrations.AddField(
            model_name='producttemplate',
            name='product_type',
            field=models.CharField(choices=[('CASHBACK', 'Cashback'), ('PRODUCT', 'Product'), ('DELIVERY_PRICE', 'Delivery Price'), ('CUPON', 'Failed')], default='PRODUCT', help_text='Type of product (e.g., cashback, product, delivery price, coupon)', max_length=20),
        ),
        migrations.AddField(
            model_name='promocode',
            name='send_odoo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='promocode',
            name='sync_status',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('synced', 'Synced')], default='created', max_length=20),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='odoo_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
