# Generated by Django 4.2.11 on 2025-06-29 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0146_alter_notification_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportcontact',
            name='support_chat_url',
            field=models.URLField(default='https://odoo.live.chat/open-live-chat/', help_text='Link to support chat (e.g., Telegram)'),
            preserve_default=False,
        ),
    ]
