# Generated by Django 4.2.11 on 2025-06-30 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0147_supportcontact_support_chat_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='branch_type',
            field=models.CharField(choices=[('REGULAR', 'Regular Branch'), ('MAIN', 'Main Branch'), ('ONLINE', 'Online Branch')], default='REGULAR', help_text='Type of the branch (e.g., Regular, Main, Online)', max_length=50),
        ),
    ]
