# Generated by Django 4.2.11 on 2025-07-01 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0148_branch_branch_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('CASHBACK', 'Cashback'), ('PRODUCT', 'Product'), ('DELIVERY_PRICE', 'Delivery Price'), ('COUPON', 'Coupon')], default='PRODUCT', help_text='Type of product (e.g., cashback, product, delivery price, coupon)', max_length=20),
        ),
        migrations.AlterField(
            model_name='producttemplate',
            name='product_type',
            field=models.CharField(choices=[('CASHBACK', 'Cashback'), ('PRODUCT', 'Product'), ('DELIVERY_PRICE', 'Delivery Price'), ('COUPON', 'Coupon')], default='PRODUCT', help_text='Type of product (e.g., cashback, product, delivery price, coupon)', max_length=20),
        ),
    ]
