# Generated by Django 4.2.11 on 2025-07-01 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0149_alter_product_product_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttemplate',
            name='description',
            field=models.TextField(blank=True, default='No description provided', null=True),
        ),
    ]
