# Generated by Django 5.2 on 2025-07-02 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0150_alter_producttemplate_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="source",
            field=models.CharField(
                choices=[
                    ("WEB", "Web"),
                    ("MOBILE", "Mobile"),
                    ("TG_MINI_APP", "Telegram Mini App"),
                ],
                default="WEB",
                max_length=20,
            ),
        ),
    ]
