# Generated by Django 4.2.11 on 2025-07-02 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0151_booking_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='oilchangedhistory',
            name='source',
            field=models.CharField(choices=[('odoo', 'Odoo'), ('django', 'Django')], default='django', max_length=50),
            preserve_default=False,
        ),
    ]
