# Generated by Django 4.2.11 on 2025-07-02 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0152_oilchangedhistory_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oilchangedhistory',
            name='source',
            field=models.CharField(choices=[('firstly', 'Firstly'), ('standard', 'Standard')], max_length=50),
        ),
    ]
