# Generated by Django 4.2.11 on 2025-07-02 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0153_alter_oilchangedhistory_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oilchangedhistory',
            name='source',
            field=models.CharField(choices=[('other', 'Other'), ('regular', 'Regular')], max_length=50),
        ),
    ]
