# Generated by Django 4.2.11 on 2025-07-02 11:16

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0154_alter_oilchangedhistory_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Product description (If empty, the product template description will be used)', null=True),
        ),
        migrations.AlterField(
            model_name='producttemplate',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, default='No description provided', null=True),
        ),
    ]
