# Generated by Django 4.2.11 on 2025-07-07 12:34

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0155_alter_product_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(blank=True, max_length=255, null=True)),
                ('title_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('title_uz', models.CharField(blank=True, max_length=255, null=True)),
                ('subtitle_en', models.CharField(blank=True, max_length=255, null=True)),
                ('subtitle_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('subtitle_uz', models.CharField(blank=True, max_length=255, null=True)),
                ('content_en', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('content_ru', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('content_uz', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('include_form', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static_page/')),
            ],
        ),
        migrations.AlterModelOptions(
            name='basketitem',
            options={'ordering': ['-id']},
        ),
    ]
