# Generated by Django 4.2.11 on 2025-07-07 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0156_staticpage_alter_basketitem_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticpage',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
    ]
