# Generated by Django 5.2 on 2025-07-08 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0159_alter_staticpage_title_en_requestform"),
    ]

    operations = [
        migrations.AddField(
            model_name="requestform",
            name="source",
            field=models.CharField(
                choices=[
                    ("WEB", "Web"),
                    ("MOBILE", "Mobile"),
                    ("TG_MINI_APP", "Telegram Mini App"),
                ],
                default="WEB",
                help_text="Source of the request",
                max_length=50,
            ),
        ),
    ]
