# Generated by Django 5.2 on 2025-07-08 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0161_requestform_odoo_id_requestform_send_odoo_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="requestform",
            name="surname",
        ),
        migrations.AddField(
            model_name="requestform",
            name="commentary",
            field=models.TextField(
                blank=True, help_text="Description of the request", null=True
            ),
        ),
    ]
