# Generated by Django 5.2 on 2025-07-15 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0162_remove_requestform_surname_requestform_commentary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loyaltyprogram",
            name="program_type",
            field=models.CharField(
                choices=[("coupons", "Coupons"), ("promo_code", "Discount Code")],
                max_length=20,
            ),
        ),
    ]
