# Generated by Django 4.2.11 on 2025-07-16 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0163_alter_loyaltyprogram_program_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_items_count',
            field=models.PositiveIntegerField(default=0, help_text='Total number of order items (for sync tracking)'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='sended_to_odoo',
            field=models.BooleanField(default=False),
        ),
    ]
