# Generated by Django 4.2.11 on 2025-07-29 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0164_order_total_items_count_orderitem_sended_to_odoo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
