# Generated by Django 4.2.11 on 2025-07-30 11:32

import app.models.product
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0165_alter_offer_end_date_alter_offer_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to=app.models.product.partner_upload_to)),
                ('name_en', models.CharField(max_length=255)),
                ('name_ru', models.CharField(max_length=255)),
                ('name_uz', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
