# Generated by Django 4.2.11 on 2025-07-30 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0166_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='telegram_bot',
            field=models.URLField(blank=True, null=True),
        ),
    ]
