# Generated by Django 4.2.11 on 2025-08-07 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0167_contact_telegram_bot'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odoo_id', models.CharField(blank=True, max_length=255, null=True)),
                ('sync_status', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('synced', 'Synced')], default='created', max_length=20)),
                ('send_odoo', models.BooleanField(default=True)),
                ('name', models.CharField(default='Unnamed Rule', max_length=255)),
                ('min_quantity', models.PositiveIntegerField(default=1)),
                ('min_amount', models.FloatField(default=0.0)),
                ('cumulative', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loyalty_rules', to='app.category')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loyalty_rules', to='app.product')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rules', to='app.loyaltyprogram')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='PromoCodeUsage',
        ),
    ]
