# Generated by Django 4.2.11 on 2025-08-11 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0168_loyaltyrule_delete_promocodeusage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loyaltyrule',
            name='name',
        ),
    ]
