# Generated by Django 4.2.11 on 2025-08-25 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0169_remove_loyaltyrule_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='promoreward',
            name='is_new_coming_reward',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='promoreward',
            name='number_of_people_case',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
