# Generated by Django 4.2.11 on 2025-09-06 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0170_promoreward_is_new_coming_reward_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companybenefit',
            name='odoo_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companybenefit',
            name='send_odoo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='companybenefit',
            name='sync_status',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('synced', 'Synced')], default='created', max_length=20),
        ),
        migrations.AddField(
            model_name='companycomment',
            name='odoo_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companycomment',
            name='send_odoo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='companycomment',
            name='sync_status',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('synced', 'Synced')], default='created', max_length=20),
        ),
        migrations.AddField(
            model_name='partner',
            name='odoo_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='send_odoo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='sync_status',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('synced', 'Synced')], default='created', max_length=20),
        ),
        migrations.AddField(
            model_name='staticpage',
            name='odoo_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='staticpage',
            name='send_odoo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='staticpage',
            name='sync_status',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('synced', 'Synced')], default='created', max_length=20),
        ),
    ]
