# Generated by Django 4.2.11 on 2025-09-15 12:19

import app.models.company_info
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0171_companybenefit_odoo_id_companybenefit_send_odoo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPageBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odoo_id', models.CharField(blank=True, max_length=255, null=True)),
                ('sync_status', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('synced', 'Synced')], default='created', max_length=20)),
                ('send_odoo', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=app.models.company_info.banner_upload_to)),
                ('link', models.URLField(blank=True, null=True)),
                ('order_number', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['order_number'],
            },
        ),
    ]
