# Generated by Django 4.2.11 on 2025-09-22 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0172_landingpagebanner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='number',
            field=models.CharField(help_text='License plate or car number (Uzbekistan)', max_length=20),
        ),
    ]
