# Generated by Django 4.2.11 on 2026-04-01 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0173_alter_car_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='EduVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('video_type', models.CharField(choices=[('url', 'Url'), ('file', 'File')], default='url', max_length=20)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='edu_videos/')),
            ],
        ),
    ]
