# Generated by Django 4.2.11 on 2026-04-02 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0174_eduvideo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eduvideo',
            old_name='description',
            new_name='description_uz',
        ),
        migrations.RenameField(
            model_name='eduvideo',
            old_name='title',
            new_name='title_uz',
        ),
        migrations.AddField(
            model_name='eduvideo',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eduvideo',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eduvideo',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='eduvideo',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
