# Generated by Django 4.2.11 on 2026-04-08 09:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0175_rename_description_eduvideo_description_uz_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('odoo_id', models.CharField(blank=True, max_length=255, null=True)),
                ('sync_status', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('synced', 'Synced')], default='created', max_length=20)),
                ('send_odoo', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unique_code', models.CharField(max_length=255, unique=True)),
                ('image', models.ImageField(upload_to='qr_codes/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
