# Generated by Django 4.2.11 on 2026-04-08 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0176_qrcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcode',
            name='odoo_id',
        ),
        migrations.RemoveField(
            model_name='qrcode',
            name='send_odoo',
        ),
        migrations.RemoveField(
            model_name='qrcode',
            name='sync_status',
        ),
    ]
