# Generated by Django 4.2.11 on 2026-04-15 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0177_remove_qrcode_odoo_id_remove_qrcode_send_odoo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=255)),
                ('name_ru', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('description_ru', models.TextField(blank=True, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='help_services/icons/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Yordam xizmati',
                'verbose_name_plural': 'Yordam xizmatlari',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='HelpServiceEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='help_services/employees/')),
                ('phone', models.CharField(max_length=30)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='app.helpservice')),
            ],
            options={
                'verbose_name': 'Yordam xizmati xodimi',
                'verbose_name_plural': 'Yordam xizmati xodimlari',
            },
        ),
    ]
