# Generated by Django 4.2.11 on 2026-04-21 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0180_videosubcategory_alter_eduvideo_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eduvideo',
            old_name='category',
            new_name='subcategory',
        ),
    ]
