# Generated by Django 4.2.11 on 2026-04-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0181_rename_category_eduvideo_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='video_categories/'),
        ),
    ]
