"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.20.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url
import os
from datetime import timedelta
from dotenv import load_dotenv
from celery.schedules import crontab
import firebase_admin
from firebase_admin import credentials

load_dotenv()
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "0") == "1"

# Use this in prod server
# ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS').split(',')

# use this is demo server
ALLOWED_HOSTS = ["*"]

CORS_ALLOW_ALL_ORIGINS = True

# If you want to allow specific origins:
CORS_ALLOWED_ORIGINS = ["http://localhost:3000", "http://127.0.0.1:8000"]

CSRF_TRUSTED_ORIGINS = [
    "https://api.car-land.uz",
    "https://www.car-land.uz",
    "https://e-commerce.smarterp.uz",
    "http://e-commerce.smarterp.uz",
    "https://demo-server.car-land.uz",
    "http://demo-server.car-land.uz",
    "https://api.carland.uz",
    "http://api.carland.uz",
]

# If you're using cookies for authentication with CORS
CORS_ALLOW_CREDENTIALS = True

MAX_ORDER_AMOUNT = os.getenv("MAX_ORDER_AMOUNT", 100000000.00)
# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # djangoapps
    "corsheaders",
    "rest_framework",
    "drf_yasg",
    "ckeditor",
    "rest_framework_simplejwt",
    "drf_spectacular",
    "rest_framework_simplejwt.token_blacklist",
    "rosetta",
    'fcm_django',
    'django_celery_beat',
    # customapps
    "app.apps.AppConfig",
    "odoo",
    "user",
]


REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.AllowAny",
    ],
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_FILTER_BACKENDS": ["django_filters.rest_framework.DjangoFilterBackend"],
    "EXCEPTION_HANDLER": "user.utils.custom_jwt_exception_handler",
}
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

SPECTACULAR_SETTINGS = {
    "TITLE": "Oilbank Ecommerce API Documentation",
    "DESCRIPTION": "Detailed documentation of all API endpoints",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "COMPONENT_SPLIT_REQUEST": True,
    "SCHEMA_PATH_PREFIX": r"/api/",
    "SECURITY": [
        {
            "Bearer": [],
        }
    ],
    "AUTHENTICATION_WHITELIST": [
        "rest_framework.authentication.SessionAuthentication",
        "rest_framework.authentication.BasicAuthentication",
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
}


SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=7),  # Token expires in 15 minutes
    "REFRESH_TOKEN_LIFETIME": timedelta(days=30),  # Refresh token expires in 1 day
    "ROTATE_REFRESH_TOKENS": False,  # Generates new refresh token on use
    "BLACKLIST_AFTER_ROTATION": False,  # Blacklist old refresh tokens
    "ALGORITHM": "HS256",  # Default hashing algorithm
    "SIGNING_KEY": SECRET_KEY,  # Uses Django's SECRET_KEY
    "AUTH_HEADER_TYPES": ("Bearer",),  # Authorization: Bearer <token>
    "VERIFYING_KEY": None,
    "AUDIENCE": None,
    "ISSUER": None,
}

AUTH_USER_MODEL = "user.User"


MIDDLEWARE = [
    # customs
    "utils.middlewares.IgnoreTokenOnLoginMiddleware",
    # defaults
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

if DEBUG:
    MIDDLEWARE.insert(
        0,
        "utils.middlewares.DevLoggerMiddleware",
    )

# paths for unlogging
DEBUG_LOGGER_EXCLUDE_PATHS = [
    "/static/",
    "/media/",
    "/favicon.ico",
]

# maximal length for log
DEBUG_LOG_MAX_LENGTH = 2000


FILE_UPLOAD_MAX_MEMORY_SIZE = 52428800
DATA_UPLOAD_MAX_MEMORY_SIZE = 52428800
MAX_UPLOAD_SIZE = 52428800

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "simple": {
            "format": "{message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
    },
    "loggers": {
        "django.request": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "django.server": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}


ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

USE_RENDER_DATABASE = os.getenv("USE_RENDER_DATABASE", "0") == "1"

if USE_RENDER_DATABASE:
    DATABASES = {
        "default": dj_database_url.config(
            default=os.getenv("DATABASE_URL"),
            conn_max_age=600,
        )
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.getenv("DB_NAME", "ecommerce"),
            "USER": os.getenv("DB_USER", "postgres"),
            "PASSWORD": os.getenv("DB_PASSWORD", "password"),
            "HOST": os.getenv("DB_HOST", "localhost"),
            "PORT": os.getenv("DB_PORT", "5432"),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Tashkent"

USE_I18N = True

USE_TZ = True

LANGUAGES = [
    ("en", _("English")),
    ("ru", _("Russian")),
    ("uz", _("Uzbek")),
]

LOCALE_PATHS = [
    os.path.join(BASE_DIR, "locale"),
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

# STATICFILES_DIRS = [
#     BASE_DIR / 'static',
# ]

STATIC_URL = "/static/"
STATIC_ROOT = os.getenv("DJANGO_STATIC_ROOT", "/home/user/web/staticfiles")

# for server use this
MEDIA_URL = "/media/"
MEDIA_ROOT = os.getenv("DJANGO_MEDIA_ROOT", "/home/user/web/media")

# for local run use this
# MEDIA_URL = "/media/"
# MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Celery settings
CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", "redis://redis:6379/0")
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND", "redis://redis:6379/0")
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'
CELERY_BEAT_MAX_LOOP_INTERVAL = 600
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = "UTC"

# Odoo API URL
ODOO_API_URL = os.getenv("ODOO_API_URL")

#delay
ODOO_SYNC_DELAY_SECONDS = 5

# SMS limit last 24 hours
SMS_LIMIT = os.getenv("SMS_LIMIT", 10)

APP_SMS_HASH = os.getenv("APP_SMS_HASH", "viT0OR0BRBl")

# Tester login settings
TESTER_LOGINS = os.getenv('TESTER_LOGINS', "").split(',')
TESTER_OTP = os.getenv('TESTER_OTP', '1111')

DATA_UPLOAD_MAX_NUMBER_FIELDS = 20000

# Multicard settings
MULTICARD_BASE_URL = os.getenv("MULTICARD_BASE_URL")
MULTICARD_APPLICATION_ID = os.getenv("MULTICARD_APPLICATION_ID")
MULTICARD_SECRET = os.getenv("MULTICARD_SECRET")

MULTICARD_STORE_ID = "954"
MULTICARD_CALLBACK_URL = "https://api.carland.uz/api/cards/callback/"
MULTICARD_REDIRECT_URL = "some-url"
MULTICARD_REDIRECT_DECLINE_URL = "some-url"
MULTICARD_DEFAULT_LANG = "uz"

# Cache settings
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": os.getenv("REDIS_CACHE_URL", "redis://redis:6379/1"),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
    }
}

CELERY_BEAT_SCHEDULE = {
    'check-all-notifications': {
        'task': 'app.tasks.run_all_notifications',
        'schedule': crontab(minute='0,30'),  # Every 30 minutes
    },
}


FCM_DJANGO_SETTINGS = {
    'default_user_field_name': 'id',  # Maps FCMDevice.user_id to User.id
}


FIREBASE_CREDENTIALS_PATH = os.path.join(BASE_DIR, 'credentials', 'carland-d17f7-firebase-adminsdk-fbsvc-673594dd35.json')

# Initialize Firebase Admin SDK
cred = credentials.Certificate(FIREBASE_CREDENTIALS_PATH)
firebase_admin.initialize_app(cred)