# Generated by Django 4.2.11 on 2025-04-08 03:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userinfo",
            name="building",
        ),
        migrations.RemoveField(
            model_name="userinfo",
            name="demophone_code",
        ),
        migrations.RemoveField(
            model_name="userinfo",
            name="floor",
        ),
        migrations.RemoveField(
            model_name="userinfo",
            name="google_link",
        ),
        migrations.RemoveField(
            model_name="userinfo",
            name="yandex_link",
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=255)),
                ("yandex_link", models.URLField(blank=True, null=True)),
                ("building", models.CharField(blank=True, max_length=255, null=True)),
                ("floor", models.IntegerField(blank=True, null=True)),
                (
                    "demophone_code",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("is_main", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="address",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
