# Generated by Django 4.2.11 on 2025-04-08 10:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_alter_address_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="messagelog",
            name="status",
            field=models.CharField(
                choices=[
                    ("SENT", "Sent"),
                    ("FAILED", "Failed"),
                    ("PENDING", "Pending"),
                ],
                default="PENDING",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="otp",
            name="phone",
            field=models.CharField(
                max_length=20,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be in correct format: +998XXXXXXXXX or 998XXXXXXXXX",
                        regex="^(\\+998|998)\\d{9}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                max_length=20,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be in correct format: +998XXXXXXXXX or 998XXXXXXXXX",
                        regex="^(\\+998|998)\\d{9}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("REGULAR", "Regular User"), ("ADMIN", "Admin")],
                default="REGULAR",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("MALE", "Male"), ("FEMALE", "Female")],
                max_length=10,
                null=True,
            ),
        ),
    ]
