# Generated by Django 4.2.11 on 2025-04-10 12:16

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_alter_messagelog_status_alter_otp_phone_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to=user.models.avatar_upload_to
            ),
        ),
    ]
