# Generated by Django 4.2.11 on 2025-04-11 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_userinfo_avatar"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userinfo",
            name="email",
        ),
    ]
