# Generated by Django 4.2.11 on 2025-04-16 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_remove_userinfo_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
