# Generated by Django 5.2 on 2025-04-24 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0007_userinfo_address"),
    ]

    operations = [
        migrations.CreateModel(
            name="MulticardConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "application_id",
                    models.CharField(default="Multicard Id", max_length=255),
                ),
                ("secret_key", models.CharField(default="Secret Id", max_length=255)),
                ("store_id", models.CharField(default="950", max_length=100)),
            ],
            options={
                "verbose_name": "Multicard Configuration",
                "verbose_name_plural": "Multicard Configurations",
            },
        ),
    ]
