# Generated by Django 4.2.11 on 2025-05-06 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0008_multicardconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="odoo_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
