# Generated by Django 4.2.11 on 2025-05-07 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0009_user_odoo_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="sync_status",
            field=models.CharField(
                choices=[
                    ("created", "created"),
                    ("updated", "updated"),
                    ("deleted", "deleted"),
                    ("synced", "synced"),
                ],
                default="created",
                max_length=20,
            ),
        ),
    ]
