# Generated by Django 4.2.11 on 2025-05-08 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0010_user_deleted_at_user_is_deleted_user_sync_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="send_odoo",
            field=models.BooleanField(default=True),
        ),
    ]
