# Generated by Django 4.2.11 on 2025-05-08 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0011_user_send_odoo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="deleted_at",
        ),
    ]
