# Generated by Django 4.2.11 on 2025-05-08 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0012_remove_user_deleted_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_deleted",
        ),
    ]
