# Generated by Django 4.2.11 on 2025-05-21 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0013_remove_user_is_deleted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="sync_status",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("updated", "Updated"),
                    ("deleted", "Deleted"),
                    ("synced", "Synced"),
                ],
                default="created",
                max_length=20,
            ),
        ),
    ]
