# Generated by Django 4.2.11 on 2025-05-26 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0082_location_branch_id"),
        ("user", "0015_alter_user_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="district",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="addresses",
                to="app.district",
            ),
        ),
        migrations.AddField(
            model_name="address",
            name="region",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="addresses",
                to="app.region",
            ),
        ),
    ]
