# Generated by Django 4.2.11 on 2025-05-26 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0016_address_district_address_region"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="address",
            name="address",
        ),
        migrations.AddField(
            model_name="address",
            name="additional",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
