# Generated by Django 4.2.11 on 2025-05-26 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0083_remove_order_address_order_address_id"),
        ("user", "0017_remove_address_address_address_additional"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="district",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="addresses",
                to="app.district",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="address",
            name="region",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="addresses",
                to="app.region",
            ),
            preserve_default=False,
        ),
    ]
