# Generated by Django 4.2.11 on 2025-05-30 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0018_alter_address_district_alter_address_region"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="name",
            field=models.CharField(
                default="Mening uyim", help_text="Your address name", max_length=255
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="address",
            name="yandex_link",
            field=models.URLField(
                default="https://yandex.uz/maps/10335/tashkent/",
                help_text="Yandex link",
            ),
            preserve_default=False,
        ),
    ]
