# Generated by Django 4.2.11 on 2025-06-02 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0019_address_name_alter_address_yandex_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="odoo_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="address",
            name="send_odoo",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="address",
            name="sync_status",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("updated", "Updated"),
                    ("deleted", "Deleted"),
                    ("synced", "Synced"),
                ],
                default="created",
                max_length=20,
            ),
        ),
    ]
