# Generated by Django 4.2.11 on 2025-06-30 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('user', '0020_address_odoo_id_address_send_odoo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagelog',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='messagelog',
            name='context',
            field=models.JSONField(blank=True, help_text="Additional context for the message, e.g., {'order_id': 123}", null=True),
        ),
        migrations.AddField(
            model_name='messagelog',
            name='message_type',
            field=models.CharField(blank=True, help_text="Type of the message, e.g., 'SMS', 'Email', etc.", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='messagelog',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
