# Generated by Django 4.2.11 on 2025-07-01 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_messagelog_content_type_messagelog_context_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='language',
            field=models.CharField(choices=[('UZ', 'Uzbek'), ('EN', 'English'), ('RU', 'Russian')], default='UZ', max_length=20),
        ),
    ]
