# Generated by Django 4.2.11 on 2025-09-03 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_userinfo_referral_count_userinfo_referral_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='is_referred',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='referral_code',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
