# Generated by Django 4.2.11 on 2026-04-01 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_userinfo_is_referred_userinfo_referral_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserShareInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_code', models.CharField(max_length=255, unique=True)),
                ('phone_number_allowed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
