# Generated by Django 4.2.11 on 2026-04-04 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_notificationmessages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificationmessages',
            old_name='message',
            new_name='message_uz',
        ),
        migrations.AddField(
            model_name='notificationmessages',
            name='message_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notificationmessages',
            name='message_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
