# Generated by Django 4.2.11 on 2026-04-08 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0176_qrcode'),
        ('user', '0027_rename_message_notificationmessages_message_uz_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usershareinfo',
            name='unique_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_info', to='app.qrcode'),
        ),
    ]
