# Generated by Django 4.2.11 on 2026-04-08 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_alter_usershareinfo_unique_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usershareinfo',
            name='phone_number_allowed',
            field=models.BooleanField(default=True),
        ),
    ]
